### ISSUE TITLE
Whitelist does not persist after reboot

### ISSUE THREAD

**Issue by astrons** [an1by/SimpleWhitelist#1]
Version:
  Velocity: 1.21 (use repository itzg/mc-proxy)
  Simplewhitelist: 0.3 for velocity1.18–1.21

Through the console, players are normally added to the whitelist, and the whitelist.txt file is updated accordingly. Everything works fine until the container is rebooted.
After reboot, when entering the rcon command
 'swl list' response 'In whitelist: Empty'
Moreover, the whitelist.txt file is not empty; it stores a list of players. When you enter the add player command, the whitelist.txt file is cleared and begins to be filled in anew as players are added to the list.

**Comment by multivarka1** [comment]
I have a similar problem. I am using the Purpur 1.21, and the plugin version 0.3. After restarting the server, the file whitelist.txt it is reset and all added players are removed from there.

**Comment by an1by** [comment]
Fixed
