### ISSUE TITLE
No 1.21.1 fabric version on modrinth

### ISSUE THREAD

**Issue by Obambulate** [an1by/SimpleWhitelist#2]
There is no 1.21.1 fabric version on modrinth. Is this a mistake?

**Comment by an1by** [comment]
This isn't mistake. I'll make support of 1.21.1 later

**Comment by DarienRahl** [comment]
Also will be there 1.12 version for Fabric?

**Comment by an1by** [comment]
> Also will be there 1.21 version for Fabric?

Working on it rn. Wait for 1 day

**Comment by an1by** [comment]
not day, only hour. Updated, new releases on [modrinth](https://modrinth.com/plugin/simplewhitelist/versions)
