### ISSUE TITLE
Whitelist is not working after server restart

### ISSUE THREAD

**Issue by KalebVargo** [an1by/SimpleWhitelist#5]
Minecraft Version : 1.21.1
Fabric Version : 0.16.5

Config:
{
    "whitelist": true,
    "databaseType": "json",
    "mysqlUrl": "jdbc:mysql://<username>:<password>@<host>:<port>/<database>",
    "jsonFileName": "simplewhitelist.json"
}

The whitelist plugin works until the server is shut off and turned back on. It's like the plugin can't read the saved whitelist anymore. All players are not whitelisted after a restart. `wsl enable` does not fix it. The players have to be `wsl add {player}` again for them to be able to re-join.

**Comment by an1by** [comment]
1. What the `wsl` command?
2. What the config? There is no mysql support.
